import type { InsightsAutomation } from '../../src/lib/types'
import { normaliseSchedule } from '../../src/lib/insightsSchedule'
import { BadRequest, isRecord, jsonNoStore, toErrorResponse } from '../lib/http'
import {
  AUTOMATION_HINT,
  readAutomation,
  readStoredReport,
  writeAutomation,
} from '../lib/insightsStore'

/**
 * The report schedule, and the last report anything wrote.
 *
 * `GET` reads both; `PUT` folds in whichever of them the caller sends. The two
 * halves are kept behind one endpoint because they are one record — a reader
 * opening the dashboard wants the settings and the report they produced in the
 * same breath, and splitting them would mean two round trips to draw one card.
 */
export default async function handler(request: Request): Promise<Response> {
  try {
    if (request.method === 'GET') {
      return jsonNoStore({ automation: await readAutomation() })
    }

    if (request.method === 'PUT') {
      const body: unknown = await request.json().catch(() => {
        throw new BadRequest('Request body must be JSON')
      })
      if (!isRecord(body)) throw new BadRequest('Request body must be an object')

      const patch: Partial<InsightsAutomation> = {}
      if (body.schedule !== undefined) {
        patch.schedule = normaliseSchedule(body.schedule)
      }
      // A report the operator generated by hand, kept so the dashboard still
      // has something to show after a reload. Stored under the same key as the
      // scheduled ones: the card shows the most recent report, and which
      // button produced it is a label on it rather than a separate shelf.
      if (body.latest !== undefined) {
        const latest = readStoredReport(body.latest)
        if (!latest) throw new BadRequest('`latest` is not a complete report')
        patch.latest = latest
      }

      if (Object.keys(patch).length === 0) {
        throw new BadRequest('Send `schedule`, `latest`, or both')
      }

      return jsonNoStore({ automation: await writeAutomation(patch) })
    }

    return jsonNoStore({ error: { message: 'Method not allowed' } }, 405)
  } catch (err) {
    return toErrorResponse(err, AUTOMATION_HINT)
  }
}
