import type {
  AdapterResult,
  InsightsAutomation,
  InsightsSchedule,
  StoredInsightsReport,
} from '../types'
import { toResult } from './client'

const SOURCE = 'Report schedule'
const HINT =
  'The schedule could not be reached. Your settings are not saved until this succeeds.'
const ENDPOINT = '/.netlify/functions/insights-schedule'

interface AutomationBody {
  automation?: InsightsAutomation
  error?: { message?: string }
}

async function request(init?: RequestInit): Promise<InsightsAutomation> {
  const res = await fetch(ENDPOINT, init)
  const text = await res.text()

  if (!(res.headers.get('content-type') ?? '').includes('application/json')) {
    throw new Error(
      'Netlify Functions are unavailable. Start local development with `npx netlify dev`.',
    )
  }

  let body: AutomationBody = {}
  try {
    body = JSON.parse(text) as AutomationBody
  } catch {
    throw new Error('The schedule store returned invalid JSON.')
  }

  if (!res.ok) {
    throw new Error(body.error?.message ?? `Request failed with status ${res.status}`)
  }
  if (!body.automation) throw new Error('The schedule store returned no settings.')
  return body.automation
}

export async function fetchAutomation(): Promise<AdapterResult<InsightsAutomation>> {
  return toResult(SOURCE, HINT, () => request())
}

/** Saves the settings alone; the stored report and last run are left as they are. */
export async function saveSchedule(
  schedule: InsightsSchedule,
): Promise<InsightsAutomation> {
  return request({
    method: 'PUT',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ schedule }),
  })
}

/**
 * Keeps a report that was generated by hand.
 *
 * Without this the card would be empty on every reload until the next
 * scheduled run — the reader would watch a report they paid for disappear
 * because they refreshed the page.
 */
export async function saveLatestReport(
  latest: StoredInsightsReport,
): Promise<InsightsAutomation> {
  return request({
    method: 'PUT',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ latest }),
  })
}
